name: build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]  # Current Java LTS
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for GitHub Releases
    outputs:
      jar-path: ${{ steps.find-jar.outputs.jar }}  # Correctly pass JAR path

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Find Release JAR
        id: find-jar
        run: echo "jar=$(ls build/libs/*.jar | head -n 1)" >> $GITHUB_OUTPUT

      - name: Capture build artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-jar
          path: ${{ steps.find-jar.outputs.jar }}  # Corrected JAR path reference

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')  # Run only on version tags
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ needs.build.outputs.jar-path }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
